### ISSUE TITLE
Jefftherobot.com:3000

### ISSUE THREAD

**Issue by mexitek** [jefftherobot/alexa-kodi-skill#1]
Is this domain and port pointing to your kodi box? For someone to reuse this, they would need their kodi box to have a public facing domain? Can't anyone force a movie to play on your kodi box by putting http://jefftherobot.com:3000/movie?title=alien in their browser?

**Comment by k0bura** [comment]
My kodi box isn't directly exposed. jefftherobot.com is just a proxy, but you're right...my service is totally exposed. I need to work on some sort of authentication mechanism since the amazon echo requires the service to be open to the internet.

**Comment by mexitek** [comment]
If you have NodeJS running on your box, you can use something like AWS IoT as a pubsub. I am doing the same thing with a mirror in my house. 

https://www.hackster.io/mexitek/magic-mirror-amazon-echo-and-aws-iot-29bba5
